### ISSUE TITLE
enum messup

### ISSUE THREAD

**Issue by RafPlayz69YT** [loypoll/OpenSpire#1]
enum 152 is unused yet not padded
enum 152 is after the rupert btw

this makes it so supergrab is 153
this breaks painter (even more i suppose)

this also breaks honey (which is suppose to be 153)

**Comment by RadixComet** [comment]
# fixed
## i think i fixed it

**Comment by RafPlayz69YT** [comment]
i dont think you did ill check

if you didn't ill just make a pr
